add setup openwrt dns transitions

diff --git a/chatbot/config/viktorwebservices.yaml b/chatbot/config/viktorwebservices.yaml
--- a/chatbot/config/viktorwebservices.yaml
+++ b/chatbot/config/viktorwebservices.yaml
@@ -63,6 +63,33 @@ commands:
   approvedBy: *admin-role
   showCmdOutput: true
 
+- &cmd-setup-openwrt-dns
+  id: "setup_openwrt_dns"
+  cmd: |
+    set -e
+    dns=$(echo $line | awk '{print $1}')
+    if [ -z "$dns" ]; then
+      echo "DNS server must not be empty"
+      exit 1
+    fi
+
+    set +e
+    out=$(infra_cli -use-case setup-openwrt-dns -new-dns "$dns" -result-only 2>&1)
+    set -e
+
+    if [ $? -ne 0 ]; then
+      echo "Error occurred while updating DNS server on OpenWRT: $out"
+      exit 1
+    fi
+
+    echo $out
+
+  prettyName: "Setup OpenWRT DNS"
+  permissions:
+    - *perm-run-shell-commands
+  approvedBy: *admin-role
+  showCmdOutput: true
+
 groups:
 - &viktor-group
   name: "viktor"
@@ -108,6 +135,16 @@ states:
     Example:
     Viktor iOcNe48FpLwOa6jBBs9686K5ViPZmLEaJ7axjGT00Xg=
   defaultHandler: *cmd-setup-wireguard
+- id: &state-setup-openwrt-dns "SetupOpenWRTDNS"
+  message: |
+      You can use this command to update OpenWRT's DNS server.
+
+      Please enter the new DNS server's IP address. 
+      Recommended values: 
+        - 10.0.20.1 (home DNS + PiHole)
+        - 1.1.1.1 (Cloudflare's DNS)
+        - 9.9.9.9
+  defaultHandler: *cmd-setup-openwrt-dns
 ###### End of Setup state machine ###### 
 
 ###### Info state machine ###### 
@@ -161,6 +198,9 @@ events:
 - id: &event-setup-wireguard "SetupVPN"
   message: "Setup VPN"
   orderID: 12
+- id: &event-setup-openwrt-dns "SetupOpenWRTDNS"
+  message: "Setup OpenWRT's DNS"
+  orderID: 13
 #### End of Setup events ####
 #### Info events ####
 - id: &event-showbloginfo "ShowBlogInfo"
@@ -223,9 +263,14 @@ statemachine:
   src: 
     - *state-setup
   dst: *state-setup-wireguard
+- name: *event-setup-openwrt-dns
+  src:
+    - *state-setup
+  dst: *state-setup-openwrt-dns
 - name: *event-back
   src:
     - *state-setup-wireguard
+    - *state-setup-openwrt-dns
   dst: *state-setup
 #### End of Setup state machine ####
 #### Info state machine ####
